#ifndef OSAL_ERROR_H
#define OSAL_ERROR_H

#define OSAL_SUCCESS                     (0)
#define OSAL_ERROR                       (1)
#define OSAL_INVALID_POINTER             (2)
#define OSAL_ERROR_ADDRESS_MISALIGNED    (3)
#define OSAL_ERROR_TIMEOUT               (4)
#define OSAL_INVALID_INT_NUM             (5)
#define OSAL_SEM_FAILURE                 (6)
#define OSAL_SEM_TIMEOUT                 (7)
#define OSAL_QUEUE_EMPTY                 (8)
#define OSAL_QUEUE_FULL                  (9)
#define OSAL_QUEUE_TIMEOUT               (10)
#define OSAL_QUEUE_INVALID_SIZE          (11)
#define OSAL_QUEUE_ID_ERROR              (12)
#define OSAL_ERR_NAME_TOO_LONG           (13)
#define OSAL_ERR_NO_FREE_IDS             (14)
#define OSAL_ERR_NAME_TAKEN              (15)
#define OSAL_ERR_INVALID_ID              (16)
#define OSAL_ERR_NAME_NOT_FOUND          (17)
#define OSAL_ERR_SEM_NOT_FULL            (18)
#define OSAL_ERR_INVALID_PRIORITY        (19)
#define OSAL_INVALID_SEM_VALUE           (20)
#define OSAL_ERR_FILE                    (27)
#define OSAL_ERR_NOT_IMPLEMENTED         (28)
#define OSAL_TIMER_ERR_INVALID_ARGS      (29)
#define OSAL_TIMER_ERR_TIMER_ID          (30)
#define OSAL_TIMER_ERR_UNAVAILABLE       (31)
#define OSAL_TIMER_ERR_INTERNAL          (32)
#define OSAL_ERR_OBJECT_IN_USE           (33)
#define OSAL_ERR_BAD_ADDRESS             (34)
#define OSAL_ERR_INCORRECT_OBJ_STATE     (35)
#define OSAL_ERR_INCORRECT_OBJ_TYPE      (36)
#define OSAL_ERR_STREAM_DISCONNECTED     (37)
#define OSAL_ERR_OPERATION_NOT_SUPPORTED (38)
#define OSAL_ERR_INVALID_SIZE            (40)
#define OSAL_ERR_OUTPUT_TOO_LARGE        (41)
#define OSAL_ERR_INVALID_ARGUMENT        (42)
#define OSAL_ERR_IN_ISR                  (43)

#endif /* OSAL_ERROR_H */
